version: '3.3'
services:
  db:
    container_name: db_2
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  web:
    container_name: web_2
    image: arseny13/culture_bot:v1.1
    restart: always
    volumes:
      - static_value:/app/core/static/
      - media_value:/app/core/media
    depends_on:
      - db
    env_file:
      - ../.env

  nginx:
    container_name: nginx_2
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

  bot:
    container_name: bot_2
    image: arseny13/culture_bot:v1.1
    restart: always
    working_dir: "/app/core"
    command: python manage.py bot
    volumes:
      - media_value:/app/core/media
    depends_on:
      - db
      - web
      - nginx
    env_file:
      - ../.env

volumes:
  static_value:
  media_value:
  postgres_data:
