# Generated by Django 4.1 on 2023-08-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='author',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='message_after_review',
            field=models.TextField(default='Спасибо! Ваше мнение очень важно для нас!', verbose_name='Сообщение после комментария пользователя'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='message_before_review',
            field=models.TextField(default='Напишите, что вы думаете об этом?', verbose_name='Сообщение перед комментарием пользователя'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='transfer_message',
            field=models.TextField(default='Отлично, идем дальше!', verbose_name='Сообщение для перехода к следующему объекту'),
        ),
    ]
