# Generated by Django 4.1 on 2023-08-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='culture.exhibit'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(upload_to='pictures', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit', to='culture.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(upload_to='pictures', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
