# Generated by Django 4.1 on 2023-08-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('userage', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('userhobby', models.CharField(max_length=150, verbose_name='Хобби')),
                ('text', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='exhibit',
            name='number',
            field=models.IntegerField(blank=True, default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit', to='culture.route'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='review',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='culture.exhibit'),
        ),
    ]
